
aws_credentials:
    access_key: 'AKIATLLBAJQSMYX4LUUZ'
    secret_key: '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'

s3_bucket_details:
    region_name: 'us-east-1'
    bucket_name: 'movie-analysis-bucket'

data:
    folder_name: data
  