
aws_credentials:
    access_key: ''
    secret_key: ''

s3_bucket_details:
    region_name: 'us-east-1'
    bucket_name: 'movie-analysis-bucket'

data:
    folder_name: data

dynamodb_table_details:
    region_name: 'us-east-1'
    table_name: 'movie-analysis-table'
    partition_key: 'id'
    sort_key: 'localized title'

  