
aws_credentials:
    access_key: ''
    secret_key: ''

s3_bucket_details:
    region_name: 'us-east-1'
    bucket_name: 'movie-analysis-bucket'

data:
    data_folder_name: data
    parquet_folder_name: parquet

dynamodb_table_details:
    region_name: 'us-east-1'
    table_name: 'movie-analysis-table'
    partition_key: 'id'
    sort_key: 'localized title'

paths:
    emr_path: '/home/hadoop/Movies_Analysis/'

athena:
    db_name: 'test'
    movie_tbl_name: 'movie'
    movie_s3_loc: 's3://movie-analysis-bucket/parquet/movie/'
    genre_tbl_name: 'genre'
    genre_s3_loc: 's3://movie-analysis-bucket/parquet/genres/'
    artist_tbl_name: 'artist'
    artist_s3_loc: 's3://movie-analysis-bucket/parquet/movie_cast/'
    music_tbl_name: 'music'
    music_s3_loc: 's3://movie-analysis-bucket/parquet/music_department/'
    director_tbl_name: 'director'
    director_s3_loc: 's3://movie-analysis-bucket/parquet/directors/'
    producer_tbl_name: 'producer'
    producer_s3_loc: 's3://movie-analysis-bucket/parquet/producers/'
    writer_tbl_name: 'writer'
    writer_s3_loc: 's3://movie-analysis-bucket/parquet/writers/'